// ============================================================
// DIETARY INDEX — Core Data
// Evidence tiers: I = multiple RCTs, II = human trials (early), III = mechanism/animal
// Health outcome codes: CVD, MET, COG, CAN, LON, GUT, WGT, INF
// ============================================================

export type EvidenceTier = "I" | "II" | "III";
export type EvidenceStrength = 0 | 1 | 2 | 3; // none, weak, moderate, strong

export interface HealthOutcome {
  code: string;
  label: string;
  shortLabel: string;
  description: string;
}

export interface Diet {
  id: number;
  name: string;
  shortName: string;
  tier: EvidenceTier;
  ahaScore: number | null;
  category: string;
  tagline: string;
  description: string;
  keyFeatures: string[];
  trialCount: number;
  topJournal: string;
  keyRef: string;
  keyRefDoi: string;
  outcomes: Record<string, EvidenceStrength>;
  tags: string[];
}

export const healthOutcomes: HealthOutcome[] = [
  { code: "CVD", label: "Cardiovascular", shortLabel: "CVD", description: "Heart disease, stroke, blood pressure, lipid profiles" },
  { code: "MET", label: "Metabolic", shortLabel: "Metabolic", description: "Type 2 diabetes, insulin resistance, blood glucose, metabolic syndrome" },
  { code: "COG", label: "Cognitive", shortLabel: "Cognitive", description: "Dementia, Alzheimer's disease, cognitive decline, brain health" },
  { code: "CAN", label: "Cancer", shortLabel: "Cancer", description: "Colorectal, breast, overall cancer risk reduction" },
  { code: "LON", label: "Longevity", shortLabel: "Longevity", description: "All-cause mortality, lifespan, healthspan" },
  { code: "GUT", label: "Gut Health", shortLabel: "Gut", description: "Microbiome diversity, dysbiosis, SCFA production, gut barrier integrity" },
  { code: "WGT", label: "Weight", shortLabel: "Weight", description: "BMI reduction, obesity prevention, body composition" },
  { code: "INF", label: "Inflammation", shortLabel: "Inflam.", description: "CRP, IL-6, TNF-α, systemic inflammatory markers" },
];

export const diets: Diet[] = [
  {
    id: 1,
    name: "Mediterranean Diet",
    shortName: "Mediterranean",
    tier: "I",
    ahaScore: 89,
    category: "Plant-Forward",
    tagline: "Olive oil, vegetables, fish, moderate wine — the most-studied dietary pattern on Earth.",
    description: "The Mediterranean dietary pattern emphasises plant foods, extra-virgin olive oil as the primary fat, moderate fish and poultry, limited red meat, and moderate wine with meals. The landmark PREDIMED trial (n=7,447) demonstrated a 30% reduction in major cardiovascular events versus a low-fat control.",
    keyFeatures: ["Extra-virgin olive oil as primary fat", "High vegetable and legume intake", "Whole grains, nuts, seeds", "Fish 2–3× per week", "Moderate red wine with meals"],
    trialCount: 4892,
    topJournal: "NEJM",
    keyRef: "Estruch R et al. Primary Prevention of Cardiovascular Disease with a Mediterranean Diet. NEJM (2018).",
    keyRefDoi: "10.1056/NEJMoa1800389",
    outcomes: { CVD: 3, MET: 3, COG: 3, CAN: 2, LON: 3, GUT: 2, WGT: 2, INF: 3 },
    tags: ["Plant-Forward", "Heart Health", "Brain Health"],
  },
  {
    id: 2,
    name: "DASH Diet",
    shortName: "DASH",
    tier: "I",
    ahaScore: 100,
    category: "Guideline-Based",
    tagline: "Designed to stop hypertension — the AHA's top-ranked eating pattern with a perfect score.",
    description: "Dietary Approaches to Stop Hypertension (DASH) was developed to reduce blood pressure without medication. It emphasises fruits, vegetables, whole grains, and low-fat dairy while strictly limiting sodium, saturated fat, and added sugars. Achieves a perfect AHA alignment score of 100.",
    keyFeatures: ["Sodium <2,300 mg/day", "High potassium, magnesium, calcium", "Fruits and vegetables 8–10 servings/day", "Low-fat dairy", "Lean proteins"],
    trialCount: 3210,
    topJournal: "NEJM",
    keyRef: "Appel LJ et al. A Clinical Trial of the Effects of Dietary Patterns on Blood Pressure. NEJM (1997).",
    keyRefDoi: "10.1056/NEJM199704173361601",
    outcomes: { CVD: 3, MET: 3, COG: 2, CAN: 2, LON: 3, GUT: 2, WGT: 2, INF: 2 },
    tags: ["Guideline-Based", "Blood Pressure", "Heart Health"],
  },
  {
    id: 3,
    name: "MIND Diet",
    shortName: "MIND",
    tier: "II",
    ahaScore: null,
    category: "Brain-Targeted",
    tagline: "Mediterranean + DASH, optimised for cognitive protection and Alzheimer's prevention.",
    description: "The Mediterranean-DASH Intervention for Neurodegenerative Delay (MIND) diet targets brain health by combining elements of Mediterranean and DASH diets with specific emphasis on berries, leafy greens, and nuts. Observational data suggests 53% lower Alzheimer's risk with strict adherence.",
    keyFeatures: ["Leafy greens ≥6 servings/week", "Berries ≥2 servings/week", "Nuts daily", "Olive oil as primary fat", "Fish ≥1×/week"],
    trialCount: 847,
    topJournal: "Alzheimer's & Dementia",
    keyRef: "Morris MC et al. MIND diet associated with reduced incidence of Alzheimer's disease. Alzheimer's & Dementia (2015).",
    keyRefDoi: "10.1016/j.jalz.2014.11.009",
    outcomes: { CVD: 2, MET: 2, COG: 3, CAN: 1, LON: 2, GUT: 2, WGT: 1, INF: 2 },
    tags: ["Brain Health", "Plant-Forward", "Hybrid"],
  },
  {
    id: 4,
    name: "Whole-Food Plant-Based",
    shortName: "WFPB",
    tier: "II",
    ahaScore: null,
    category: "Plant-Forward",
    tagline: "Unprocessed plants only — strong cardiovascular reversal and metabolic evidence.",
    description: "The whole-food plant-based diet eliminates all animal products and processed foods, focusing exclusively on vegetables, fruits, whole grains, legumes, nuts, and seeds in minimally processed forms. Strong evidence for cardiovascular risk reversal and metabolic improvement.",
    keyFeatures: ["No animal products", "No refined oils or sugars", "Whole grains only", "Legumes as primary protein", "Nutrient-dense caloric profile"],
    trialCount: 1240,
    topJournal: "JAMA",
    keyRef: "Ornish D et al. Intensive lifestyle changes for reversal of coronary heart disease. JAMA (1998).",
    keyRefDoi: "10.1001/jama.280.23.2001",
    outcomes: { CVD: 3, MET: 3, COG: 1, CAN: 2, LON: 2, GUT: 3, WGT: 3, INF: 2 },
    tags: ["Plant-Forward", "Heart Health", "Metabolic"],
  },
  {
    id: 5,
    name: "Vegan Diet",
    shortName: "Vegan",
    tier: "II",
    ahaScore: 78,
    category: "Plant-Forward",
    tagline: "No animal products — strong metabolic benefits; B12 supplementation required.",
    description: "The vegan diet excludes all animal-derived foods. Strong evidence for weight loss, LDL reduction, and T2D prevention. Restrictive nature raises long-term adherence concerns and increases risk of vitamin B12, iron, zinc, and omega-3 deficiencies without supplementation.",
    keyFeatures: ["No meat, dairy, or eggs", "High fibre intake", "B12 supplementation required", "Potential omega-3 gap", "Strong weight-loss evidence"],
    trialCount: 1580,
    topJournal: "JAMA Internal Medicine",
    keyRef: "Kahleova H et al. Vegetarian diet improves insulin resistance and oxidative stress. JAMA Intern Med (2011).",
    keyRefDoi: "10.1001/archinternmed.2011.272",
    outcomes: { CVD: 2, MET: 3, COG: 1, CAN: 2, LON: 2, GUT: 2, WGT: 3, INF: 2 },
    tags: ["Plant-Forward", "Metabolic", "Weight"],
  },
  {
    id: 6,
    name: "Vegetarian Diet",
    shortName: "Vegetarian",
    tier: "II",
    ahaScore: 86,
    category: "Plant-Forward",
    tagline: "Plants and dairy/eggs — balanced nutrition with broad, consistent health benefits.",
    description: "Vegetarian diets exclude meat and fish but typically include dairy and eggs (lacto-ovo). Associated with lower BMI, reduced CVD risk, and lower cancer incidence versus omnivorous diets. More nutritionally complete than vegan diets with fewer supplementation requirements.",
    keyFeatures: ["No meat or fish", "Dairy and eggs permitted", "High plant food variety", "Lower saturated fat intake", "Adequate B12 from dairy/eggs"],
    trialCount: 2100,
    topJournal: "JAMA Internal Medicine",
    keyRef: "Orlich MJ et al. Vegetarian dietary patterns and mortality in Adventist Health Study 2. JAMA Intern Med (2013).",
    keyRefDoi: "10.1001/jamainternmed.2013.6473",
    outcomes: { CVD: 2, MET: 2, COG: 1, CAN: 2, LON: 2, GUT: 2, WGT: 2, INF: 2 },
    tags: ["Plant-Forward", "Heart Health", "Longevity"],
  },
  {
    id: 7,
    name: "Pescatarian Diet",
    shortName: "Pescatarian",
    tier: "II",
    ahaScore: 92,
    category: "Plant-Forward",
    tagline: "Plants plus seafood — near-Mediterranean evidence profile, second-highest AHA score.",
    description: "The pescatarian diet combines a plant-based foundation with seafood, providing omega-3 fatty acids (EPA/DHA) that are difficult to obtain from purely plant sources. Scores 92 on the AHA scale — second only to DASH — with strong cardiovascular and anti-inflammatory evidence.",
    keyFeatures: ["Fish and seafood as primary protein", "High omega-3 EPA/DHA intake", "No land-animal meat", "Plant-food foundation", "Dairy and eggs often included"],
    trialCount: 890,
    topJournal: "BMJ",
    keyRef: "Tong TYN et al. Risks of ischaemic heart disease and stroke in meat eaters, fish eaters, and vegetarians. BMJ (2019).",
    keyRefDoi: "10.1136/bmj.l4897",
    outcomes: { CVD: 3, MET: 2, COG: 2, CAN: 2, LON: 2, GUT: 2, WGT: 2, INF: 3 },
    tags: ["Plant-Forward", "Heart Health", "Omega-3"],
  },
  {
    id: 8,
    name: "Ketogenic Diet",
    shortName: "Keto",
    tier: "II",
    ahaScore: 31,
    category: "Low-Carbohydrate",
    tagline: "Very low carb, high fat — strong short-term metabolic effects; long-term CVD data limited.",
    description: "The ketogenic diet restricts carbohydrates to <50g/day, inducing nutritional ketosis. Strong short-term evidence for weight loss, T2D glycaemic control, and epilepsy management. Long-term cardiovascular safety remains debated due to high saturated fat intake and LDL elevation in some individuals.",
    keyFeatures: ["<50g carbohydrates/day", "Fat 60–75% of calories", "Nutritional ketosis", "Rapid initial weight loss", "Therapeutic for epilepsy (Tier I)"],
    trialCount: 1420,
    topJournal: "Annals of Internal Medicine",
    keyRef: "Westman EC et al. The effect of a low-carbohydrate, ketogenic diet versus a low-glycemic index diet on glycemic control. Ann Intern Med (2008).",
    keyRefDoi: "10.7326/0003-4819-148-4-200802190-00004",
    outcomes: { CVD: 1, MET: 3, COG: 1, CAN: 1, LON: 1, GUT: 1, WGT: 3, INF: 1 },
    tags: ["Low-Carbohydrate", "Metabolic", "Weight"],
  },
  {
    id: 9,
    name: "Low-Carbohydrate Diet",
    shortName: "Low-Carb",
    tier: "II",
    ahaScore: 64,
    category: "Low-Carbohydrate",
    tagline: "Moderate carb restriction — metabolic benefits without full ketosis.",
    description: "Low-carbohydrate diets restrict carbohydrates to 50–130g/day without requiring ketosis. Effective for weight loss and glycaemic control in T2D. The AHA scores this pattern at 64, noting concerns about restricted fruit, grain, and legume intake reducing fibre and increasing saturated fat.",
    keyFeatures: ["50–130g carbohydrates/day", "Higher protein intake", "Reduced fruit and grain intake", "Moderate fat", "Flexible food choices"],
    trialCount: 2340,
    topJournal: "NEJM",
    keyRef: "Shai I et al. Weight loss with a low-carbohydrate, Mediterranean, or low-fat diet. NEJM (2008).",
    keyRefDoi: "10.1056/NEJMoa0708681",
    outcomes: { CVD: 1, MET: 3, COG: 1, CAN: 1, LON: 1, GUT: 1, WGT: 3, INF: 1 },
    tags: ["Low-Carbohydrate", "Metabolic", "Weight"],
  },
  {
    id: 10,
    name: "Paleo Diet",
    shortName: "Paleo",
    tier: "III",
    ahaScore: 53,
    category: "Ancestral",
    tagline: "Pre-agricultural foods — theoretical rationale; limited long-term RCT evidence.",
    description: "The Paleolithic diet mimics presumed ancestral eating by emphasising lean meats, fish, vegetables, fruits, and nuts while eliminating grains, legumes, dairy, and processed foods. Short-term trials show weight loss and metabolic improvement, but long-term RCT evidence is absent.",
    keyFeatures: ["No grains or legumes", "No dairy", "Lean meats and fish", "Vegetables, fruits, nuts", "Eliminates processed foods"],
    trialCount: 340,
    topJournal: "European Journal of Clinical Nutrition",
    keyRef: "Jönsson T et al. Beneficial effects of a Paleolithic diet on cardiovascular risk factors in type 2 diabetes. Cardiovasc Diabetol (2009).",
    keyRefDoi: "10.1186/1475-2840-8-35",
    outcomes: { CVD: 1, MET: 2, COG: 0, CAN: 0, LON: 1, GUT: 1, WGT: 2, INF: 1 },
    tags: ["Ancestral", "Low-Carbohydrate", "Weight"],
  },
  {
    id: 11,
    name: "Carnivore Diet",
    shortName: "Carnivore",
    tier: "III",
    ahaScore: null,
    category: "Ancestral",
    tagline: "Animal products only — anecdotal reports; no controlled trial evidence exists.",
    description: "The carnivore diet consists exclusively of animal products. No peer-reviewed RCTs have evaluated long-term health outcomes. Evidence is limited to case reports, surveys, and mechanistic speculation. Significant concerns regarding fibre deficiency, microbiome disruption, and cardiovascular risk.",
    keyFeatures: ["Animal products only", "Zero plant foods", "High protein and fat", "No fibre intake", "No controlled trial evidence"],
    trialCount: 12,
    topJournal: "Current Opinion in Endocrinology",
    keyRef: "O'Hearn LA. Can a carnivore diet provide all essential nutrients? Curr Opin Endocrinol (2020).",
    keyRefDoi: "10.1097/MED.0000000000000576",
    outcomes: { CVD: 0, MET: 1, COG: 0, CAN: 0, LON: 0, GUT: 0, WGT: 1, INF: 0 },
    tags: ["Ancestral", "Elimination"],
  },
  {
    id: 12,
    name: "Intermittent Fasting (16:8)",
    shortName: "IF 16:8",
    tier: "II",
    ahaScore: null,
    category: "Time-Restricted",
    tagline: "16-hour fasts, 8-hour eating window — metabolic and weight benefits emerging from RCTs.",
    description: "Time-restricted eating (TRE) confines all caloric intake to an 8-hour window, inducing a daily 16-hour fast. Growing RCT evidence supports weight loss, improved insulin sensitivity, and reduced inflammatory markers. Long-term cardiovascular data remains limited.",
    keyFeatures: ["16-hour daily fast", "8-hour eating window", "No caloric restriction required", "Circadian rhythm alignment", "Flexible food choices"],
    trialCount: 780,
    topJournal: "Cell Metabolism",
    keyRef: "Sutton EF et al. Early time-restricted feeding improves insulin sensitivity, blood pressure, and oxidative stress. Cell Metab (2018).",
    keyRefDoi: "10.1016/j.cmet.2018.04.010",
    outcomes: { CVD: 1, MET: 3, COG: 1, CAN: 1, LON: 2, GUT: 1, WGT: 3, INF: 2 },
    tags: ["Time-Restricted", "Metabolic", "Weight"],
  },
  {
    id: 13,
    name: "Portfolio Diet",
    shortName: "Portfolio",
    tier: "I",
    ahaScore: null,
    category: "Cholesterol-Targeted",
    tagline: "Four cholesterol-lowering food groups — LDL reduction comparable to first-generation statins.",
    description: "The Portfolio Diet combines four evidence-based food groups that each independently lower LDL cholesterol: plant sterols, soy protein, viscous fibre, and nuts. The combination achieves LDL reductions of 20–30%, comparable to first-generation statin therapy.",
    keyFeatures: ["Plant sterols 2g/day", "Soy protein 50g/day", "Viscous fibre 20g/day", "Nuts one handful/day", "Additive LDL-lowering effect"],
    trialCount: 680,
    topJournal: "JAMA",
    keyRef: "Jenkins DJ et al. Effects of a dietary portfolio of cholesterol-lowering foods vs lovastatin on serum lipids. JAMA (2003).",
    keyRefDoi: "10.1001/jama.290.4.502",
    outcomes: { CVD: 3, MET: 2, COG: 0, CAN: 1, LON: 2, GUT: 2, WGT: 1, INF: 2 },
    tags: ["Cholesterol-Targeted", "Heart Health"],
  },
  {
    id: 14,
    name: "Nordic Diet",
    shortName: "Nordic",
    tier: "II",
    ahaScore: null,
    category: "Regional",
    tagline: "Scandinavian whole foods — comparable to Mediterranean with northern-climate ingredients.",
    description: "The New Nordic Diet emphasises locally sourced Scandinavian foods: whole grains (rye and oats), fatty fish, root vegetables, berries, and rapeseed oil. RCTs demonstrate cardiovascular and metabolic benefits comparable to the Mediterranean diet in northern European populations.",
    keyFeatures: ["Rye and oat whole grains", "Fatty fish (herring, mackerel, salmon)", "Root vegetables and berries", "Rapeseed oil as primary fat", "Minimal processed foods"],
    trialCount: 560,
    topJournal: "American Journal of Clinical Nutrition",
    keyRef: "Adamsson V et al. Effects of a healthy Nordic diet on cardiovascular risk factors. J Intern Med (2011).",
    keyRefDoi: "10.1111/j.1365-2796.2010.02290.x",
    outcomes: { CVD: 2, MET: 2, COG: 1, CAN: 1, LON: 2, GUT: 2, WGT: 2, INF: 2 },
    tags: ["Regional", "Heart Health", "Plant-Forward"],
  },
  {
    id: 15,
    name: "Longevity Diet",
    shortName: "Longevity",
    tier: "II",
    ahaScore: null,
    category: "Longevity-Targeted",
    tagline: "Valter Longo's protocol — plant-based, time-restricted, with periodic fasting-mimicking cycles.",
    description: "Developed by Valter Longo at USC, the Longevity Diet combines a predominantly plant-based diet with a 12-hour eating window and periodic 5-day fasting-mimicking diet (FMD) cycles. Backed by mechanistic data on mTOR inhibition and IGF-1 reduction, with emerging human trial evidence.",
    keyFeatures: ["Predominantly plant-based", "12-hour eating window", "Periodic 5-day FMD cycles", "Low protein 0.7g/kg/day", "Legumes as primary protein"],
    trialCount: 340,
    topJournal: "Cell",
    keyRef: "Longo VD & Anderson RM. Nutrition, longevity and disease: from molecular mechanisms to interventions. Cell (2022).",
    keyRefDoi: "10.1016/j.cell.2022.04.002",
    outcomes: { CVD: 2, MET: 2, COG: 1, CAN: 2, LON: 3, GUT: 2, WGT: 2, INF: 2 },
    tags: ["Longevity-Targeted", "Time-Restricted", "Plant-Forward"],
  },
];

export const categories = Array.from(new Set(diets.map(d => d.category)));
export const allTags = Array.from(new Set(diets.flatMap(d => d.tags)));

export const keyStats = {
  dietsIndexed: diets.length,
  trialsAnalysed: diets.reduce((sum, d) => sum + d.trialCount, 0).toLocaleString(),
  outcomeDomains: healthOutcomes.length,
  tierICount: diets.filter(d => d.tier === "I").length,
};

export const researchPapers = [
  {
    id: 1,
    journal: "NEJM",
    date: "2018-06-21",
    tier: "I" as EvidenceTier,
    readTime: "12 min",
    title: "Primary Prevention of Cardiovascular Disease with a Mediterranean Diet Supplemented with Extra-Virgin Olive Oil or Nuts",
    authors: "Estruch R, Ros E, Salas-Salvadó J … Martínez-González MA",
    whatDid: "In a randomised trial of 7,447 participants at high cardiovascular risk, assignment to a Mediterranean diet supplemented with extra-virgin olive oil (1L/week) or mixed nuts (30g/day) reduced the incidence of major cardiovascular events by approximately 30% versus a low-fat control diet over a median follow-up of 4.8 years.",
    whatMeans: "The PREDIMED trial provides the strongest RCT evidence that a specific dietary pattern — not merely nutrient manipulation — can prevent cardiovascular disease. The effect size is comparable to statin therapy in primary prevention populations.",
    doi: "10.1056/NEJMoa1800389",
    tags: ["Mediterranean", "CVD", "RCT"],
  },
  {
    id: 2,
    journal: "Cell",
    date: "2022-04-28",
    tier: "II" as EvidenceTier,
    readTime: "18 min",
    title: "Nutrition, Longevity and Disease: From Molecular Mechanisms to Interventions",
    authors: "Longo VD, Anderson RM",
    whatDid: "A comprehensive review integrating data from model organisms, epidemiological studies, and clinical trials to propose a unified framework for how dietary composition and timing affect longevity pathways — including mTOR, IGF-1, AMPK, and sirtuins.",
    whatMeans: "Longo and Anderson argue that a predominantly plant-based diet with moderate protein, periodic fasting-mimicking cycles, and a 12-hour eating window represents the most evidence-supported longevity protocol currently available for humans.",
    doi: "10.1016/j.cell.2022.04.002",
    tags: ["Longevity", "Fasting", "mTOR"],
  },
  {
    id: 3,
    journal: "Alzheimer's & Dementia",
    date: "2015-09-01",
    tier: "II" as EvidenceTier,
    readTime: "10 min",
    title: "MIND Diet Associated with Reduced Incidence of Alzheimer's Disease",
    authors: "Morris MC, Tangney CC, Wang Y … Aggarwal NT",
    whatDid: "In a prospective cohort of 923 older adults followed for an average of 4.5 years, strict adherence to the MIND diet was associated with a 53% lower rate of Alzheimer's disease compared to low adherence, after adjusting for confounders including age, education, and physical activity.",
    whatMeans: "The MIND diet's specific emphasis on leafy greens and berries — beyond the broader Mediterranean or DASH patterns — appears to confer additional neuroprotective benefit. However, RCT confirmation is still awaited from the ongoing MIND-LEAP trial.",
    doi: "10.1016/j.jalz.2014.11.009",
    tags: ["MIND", "Cognitive", "Alzheimer's"],
  },
];

export const glossaryTerms = [
  {
    id: 1,
    term: "Evidence Tier",
    definition: "A classification of the strength of scientific evidence supporting a dietary intervention. Tier I: multiple well-controlled RCTs with consistent results. Tier II: early human trials or single large RCTs. Tier III: mechanistic data, animal studies, or observational evidence only.",
    ref: "Gardner CD et al. Dietary Patterns and Cardiovascular Disease. Circulation (2023).",
    refDoi: "10.1161/CIR.0000000000001031",
  },
  {
    id: 2,
    term: "Dietary Inflammatory Index (DII)",
    definition: "A literature-derived score that characterises the overall inflammatory potential of an individual's diet. Foods and nutrients are assigned pro- or anti-inflammatory scores based on their effect on six inflammatory biomarkers: IL-1β, IL-4, IL-6, IL-10, TNF-α, and CRP.",
    ref: "Shivappa N et al. Designing and developing a literature-derived, population-based dietary inflammatory index. Public Health Nutr (2014).",
    refDoi: "10.1017/S1368980013002115",
  },
  {
    id: 3,
    term: "AHA Dietary Alignment Score",
    definition: "A 0–100 score developed by the American Heart Association to quantify how closely a dietary pattern aligns with AHA cardiovascular health guidance. Criteria include sodium, added sugar, alcohol, processed foods, vegetables, fruits, whole grains, legumes, and protein source quality.",
    ref: "Gardner CD et al. Food and Beverage Intake and Cardiovascular Health. Circulation (2023).",
    refDoi: "10.1161/CIR.0000000000001031",
  },
  {
    id: 4,
    term: "mTORC1",
    definition: "Mechanistic target of rapamycin complex 1 — a nutrient-sensing kinase that integrates amino acid availability, energy status, and growth factor signals to regulate protein synthesis, autophagy, and cellular growth. Chronic over-activation by high-protein diets is associated with accelerated cellular aging.",
    ref: "Laplante M & Sabatini DM. mTOR signaling in growth control and disease. Cell (2012).",
    refDoi: "10.1016/j.cell.2012.03.017",
  },
  {
    id: 5,
    term: "Fasting-Mimicking Diet (FMD)",
    definition: "A 5-day periodic dietary protocol providing 700–1,100 kcal/day with specific macronutrient ratios designed to activate fasting-associated cellular programmes (autophagy, IGF-1 reduction, ketone production) while allowing food intake. Developed by Valter Longo at USC.",
    ref: "Brandhorst S et al. A periodic diet that mimics fasting promotes multi-system regeneration. Cell Metab (2015).",
    refDoi: "10.1016/j.cmet.2015.05.012",
  },
  {
    id: 6,
    term: "Gut Microbiome Diversity",
    definition: "A measure of the richness and evenness of microbial species in the gastrointestinal tract. Higher diversity is consistently associated with better metabolic health, lower inflammation, and reduced risk of chronic disease. Plant-rich diets high in fibre are the strongest dietary predictor of microbiome diversity.",
    ref: "Sonnenburg JL & Bäckhed F. Diet–microbiota interactions as moderators of human metabolism. Nature (2016).",
    refDoi: "10.1038/nature18846",
  },
];
