// Dietary Index — Video Channel data
// 20 curated authoritative dietary science interviews and lectures

export interface DietaryVideo {
  id: string;
  title: string;
  channel: string;
  duration: string;
  year: number;
  speaker: string;
  speakerShort: string;
  description: string;
  topics: string[];
  takeaways: string[];
  relatedDiets: string[];
  youtubeId: string;
  thumbnailUrl?: string;
}

export const SPEAKER_FILTERS = [
  "All",
  "Willett",
  "Gardner",
  "Spector",
  "Hyman",
  "Attia",
  "Norton",
  "Lyon",
  "Patrick",
  "Katz",
  "Lustig",
  "Huberman",
  "Longo",
  "Mozaffarian",
  "Hu",
  "Segal",
  "Hall",
  "Ludwig",
  "Panda",
  "Nestle",
  "Barnard",
  "Ornish",
];

export const TOPIC_FILTERS = [
  "All topics",
  "Mediterranean Diet",
  "Gut Microbiome",
  "Metabolic Health",
  "Plant-Based Diets",
  "Protein & Muscle",
  "Intermittent Fasting",
  "Cardiovascular Health",
  "Weight Management",
  "Cognitive Health",
  "Cancer Prevention",
  "Inflammation",
  "Micronutrients",
  "Ultra-Processed Foods",
  "Dietary Patterns",
  "Food Policy",
  "Personalised Nutrition",
  "Circadian Biology",
  "Longevity",
  "Phytonutrients",
];

export const dietaryVideos: DietaryVideo[] = [
  {
    id: "v01",
    title: "The Mediterranean Diet: What the Evidence Actually Shows",
    channel: "Harvard T.H. Chan School of Public Health",
    duration: "1h 12m",
    year: 2024,
    speaker: "Walter Willett",
    speakerShort: "Willett",
    description:
      "Dr Walter Willett, Professor of Epidemiology and Nutrition at Harvard, presents the full epidemiological case for the Mediterranean dietary pattern — from the Seven Countries Study through the PREDIMED trial. He covers the specific components that drive benefit (olive oil, legumes, fish, vegetables), the evidence on cardiovascular mortality, and why dietary pattern matters more than any single nutrient.",
    topics: ["Mediterranean Diet", "Cardiovascular Health", "Dietary Patterns"],
    takeaways: [
      "PREDIMED trial showed 30% reduction in major cardiovascular events with Mediterranean diet supplemented with olive oil or nuts",
      "Olive oil is the single most evidence-backed component — extra virgin at ≥4 tablespoons/day",
      "Red and processed meat are the components most consistently associated with harm",
      "Dietary pattern adherence matters more than individual food swaps",
    ],
    relatedDiets: ["Mediterranean Diet", "DASH Protocol"],
    youtubeId: "LcDsjjkKqZw",
  },
  {
    id: "v02",
    title: "DIETFITS: Low-Fat vs Low-Carb — What a Randomised Trial Actually Found",
    channel: "Stanford Medicine",
    duration: "58m",
    year: 2023,
    speaker: "Christopher Gardner",
    speakerShort: "Gardner",
    description:
      "Dr Christopher Gardner, Director of Nutrition Studies at Stanford Prevention Research Center, presents the DIETFITS trial — a year-long RCT comparing healthy low-fat vs healthy low-carb diets in 609 adults. He covers the surprising null result on weight loss, the enormous individual variation in response, and what the data suggest about personalised nutrition.",
    topics: ["Weight Management", "Dietary Patterns", "Metabolic Health"],
    takeaways: [
      "DIETFITS found no significant difference in weight loss between healthy low-fat and healthy low-carb at 12 months",
      "Individual variation was enormous — some lost 27kg, others gained 9kg on identical diets",
      "Diet quality (whole foods, minimal processing) predicted success more than macronutrient ratio",
      "Insulin secretion and genotype did not predict differential response in this trial",
    ],
    relatedDiets: ["Low-Carbohydrate Diet", "Low-Fat Diet"],
    youtubeId: "hZ76Cg-Emw8",
  },
  {
    id: "v03",
    title: "The Gut Microbiome: Diet, Disease, and the Evidence",
    channel: "ZOE Science & Nutrition",
    duration: "1h 4m",
    year: 2024,
    speaker: "Tim Spector",
    speakerShort: "Spector",
    description:
      "Professor Tim Spector, co-founder of ZOE and Professor of Genetic Epidemiology at King's College London, covers the current state of microbiome science. He presents data from the PREDICT studies on postprandial metabolic responses, the role of dietary fibre and fermented foods, and why the gut microbiome is now considered a key mediator of diet-disease relationships.",
    topics: ["Gut Microbiome", "Dietary Patterns", "Metabolic Health"],
    takeaways: [
      "PREDICT studies show that two people eating identical meals can have dramatically different blood sugar and fat responses",
      "Plant diversity (30+ different plants per week) is the strongest predictor of microbiome diversity",
      "Fermented foods (yogurt, kefir, kimchi) consistently increase microbiome diversity in RCTs",
      "Ultra-processed foods reduce microbiome diversity within days",
    ],
    relatedDiets: ["Mediterranean Diet", "Plant-Based Diet"],
    youtubeId: "iRxbxmjjjdw",
  },
  {
    id: "v04",
    title: "Ultra-Processed Foods: The Science of Why They're Harmful",
    channel: "ZOE Science & Nutrition",
    duration: "52m",
    year: 2023,
    speaker: "Tim Spector",
    speakerShort: "Spector",
    description:
      "Spector reviews the NOVA classification system, the NIH ultra-processed food RCT by Kevin Hall showing spontaneous caloric overconsumption of 500 kcal/day on UPF diets, and the epidemiological evidence linking UPF intake to obesity, type 2 diabetes, cardiovascular disease, and all-cause mortality.",
    topics: ["Ultra-Processed Foods", "Weight Management", "Metabolic Health"],
    takeaways: [
      "The only RCT of ultra-processed vs unprocessed diets (Hall et al., Cell Metabolism 2019) showed 500 kcal/day excess intake on UPF diet despite matched macronutrients",
      "UPF consumption now accounts for >50% of calories in the UK and US",
      "NOVA classification (1–4) is more predictive of health outcomes than nutrient profiling alone",
      "Emulsifiers and artificial sweeteners may disrupt gut microbiome independently of caloric content",
    ],
    relatedDiets: ["Whole Food Diet", "Mediterranean Diet"],
    youtubeId: "kBvhtgucc5s",
  },
  {
    id: "v05",
    title: "Protein: How Much Do You Actually Need?",
    channel: "Layne Norton",
    duration: "45m",
    year: 2023,
    speaker: "Layne Norton",
    speakerShort: "Norton",
    description:
      "Dr Layne Norton, PhD in nutritional sciences, reviews the evidence on protein requirements for muscle maintenance, fat loss, and metabolic health. He addresses the RDA of 0.8g/kg as a minimum for survival (not an optimum), the leucine threshold for muscle protein synthesis, and why protein distribution across meals matters as much as total intake.",
    topics: ["Protein & Muscle", "Weight Management", "Dietary Patterns"],
    takeaways: [
      "The RDA of 0.8g/kg is a minimum to prevent deficiency — optimal for muscle maintenance is 1.6–2.2g/kg",
      "Leucine threshold (~2.5g per meal) is required to maximally stimulate muscle protein synthesis",
      "Protein is the most satiating macronutrient — high-protein diets consistently reduce ad libitum caloric intake",
      "Protein distribution matters: 3–4 meals with ≥30g protein each is superior to front- or back-loading",
    ],
    relatedDiets: ["High-Protein Diet", "Mediterranean Diet"],
    youtubeId: "ePxCeKXsD44",
  },
  {
    id: "v06",
    title: "Why Muscle is the Organ of Metabolic Health",
    channel: "Gabrielle Lyon",
    duration: "1h 2m",
    year: 2023,
    speaker: "Gabrielle Lyon",
    speakerShort: "Lyon",
    description:
      "Dr Gabrielle Lyon, founder of muscle-centric medicine, argues that skeletal muscle is the primary organ of metabolic health and longevity. She covers the evidence for protein intake, resistance training, and why the clinical focus on fat loss is misplaced — the real target is muscle gain and preservation.",
    topics: ["Protein & Muscle", "Metabolic Health", "Dietary Patterns"],
    takeaways: [
      "Skeletal muscle accounts for 80% of insulin-mediated glucose disposal — muscle mass is the primary determinant of insulin sensitivity",
      "Muscle protein synthesis requires both adequate protein (≥30g leucine-rich per meal) and resistance exercise stimulus",
      "Sarcopenia (age-related muscle loss) begins in the 30s and accelerates after 60 — prevention requires proactive protein intake",
      "Animal proteins have higher leucine content and bioavailability than most plant proteins",
    ],
    relatedDiets: ["High-Protein Diet", "Mediterranean Diet"],
    youtubeId: "WFcYF_pxLgA",
  },
  {
    id: "v07",
    title: "Intermittent Fasting and Time-Restricted Eating: The Evidence",
    channel: "Huberman Lab",
    duration: "2h 8m",
    year: 2023,
    speaker: "Andrew Huberman",
    speakerShort: "Huberman",
    description:
      "Huberman covers the neuroscience and metabolic science of intermittent fasting and time-restricted eating (TRE). He reviews the Satchidananda Panda lab data on circadian alignment of food intake, the TREAT trial (TRE vs unrestricted eating in adults with obesity), and provides an evidence-based protocol for implementing TRE.",
    topics: ["Intermittent Fasting", "Metabolic Health", "Weight Management"],
    takeaways: [
      "Time-restricted eating aligned with daylight hours (eating window 8am–6pm) improves metabolic markers independent of caloric restriction",
      "The TREAT trial found no significant weight loss advantage of 16:8 TRE vs unrestricted eating — but adherence was low",
      "Early TRE (eating earlier in the day) is more metabolically beneficial than late TRE",
      "Circadian misalignment (eating late at night) disrupts insulin sensitivity and lipid metabolism",
    ],
    relatedDiets: ["Intermittent Fasting", "Time-Restricted Eating"],
    youtubeId: "9tRohh0gErM",
  },
  {
    id: "v08",
    title: "The Fasting Mimicking Diet: Human Trial Data",
    channel: "Huberman Lab",
    duration: "2h 22m",
    year: 2022,
    speaker: "Valter Longo",
    speakerShort: "Longo",
    description:
      "Dr Valter Longo, Director of the USC Longevity Institute, presents the science behind the Fasting Mimicking Diet (FMD) — a 5-day, low-calorie protocol that triggers autophagy and stem cell regeneration. He covers the human trial data showing reductions in biological age markers, IGF-1, visceral fat, and inflammatory markers after 3 monthly FMD cycles.",
    topics: ["Intermittent Fasting", "Dietary Patterns", "Inflammation"],
    takeaways: [
      "3 monthly cycles of FMD (800–1100 kcal/day for 5 days) reduced biological age by 2.5 years in a randomised trial",
      "FMD reduces IGF-1, glucose, and CRP while increasing stem cell markers",
      "The 5-day duration appears to be the minimum required to trigger meaningful autophagy in humans",
      "Refeeding after FMD drives stem cell-based regeneration — the combination is more powerful than fasting alone",
    ],
    relatedDiets: ["Fasting Mimicking Diet", "Intermittent Fasting"],
    youtubeId: "FXbanqer1fQ",
  },
  {
    id: "v09",
    title: "Cardiovascular Disease and Diet: What the Evidence Says",
    channel: "Peter Attia MD",
    duration: "1h 48m",
    year: 2023,
    speaker: "Peter Attia",
    speakerShort: "Attia",
    description:
      "Attia presents the lipid hypothesis, the role of ApoB and LDL-P in atherosclerosis, and how dietary choices affect cardiovascular risk. He covers the evidence on saturated fat, dietary cholesterol, omega-3 fatty acids, and why he believes ApoB testing should be universal. He also discusses the REDUCE-IT trial and the controversy around high-dose omega-3.",
    topics: ["Cardiovascular Health", "Dietary Patterns", "Micronutrients"],
    takeaways: [
      "ApoB (not LDL-C) is the most predictive lipid marker for cardiovascular events",
      "Saturated fat raises LDL-C but the effect on ApoB and cardiovascular outcomes is more complex and diet-context-dependent",
      "REDUCE-IT showed 25% reduction in cardiovascular events with 4g/day EPA — but mineral oil placebo is controversial",
      "Replacing saturated fat with refined carbohydrates does not reduce cardiovascular risk",
    ],
    relatedDiets: ["Mediterranean Diet", "DASH Protocol"],
    youtubeId: "MAw4KMoBTPo",
  },
  {
    id: "v10",
    title: "Sugar, Insulin, and Metabolic Disease",
    channel: "University of California Television",
    duration: "1h 29m",
    year: 2023,
    speaker: "Robert Lustig",
    speakerShort: "Lustig",
    description:
      "Dr Robert Lustig, Professor of Pediatric Endocrinology at UCSF, presents his case that fructose — not fat — is the primary driver of metabolic syndrome. He covers the hepatic metabolism of fructose vs glucose, the role of added sugars in driving insulin resistance, and the evidence linking sugar-sweetened beverage consumption to type 2 diabetes and cardiovascular disease.",
    topics: ["Metabolic Health", "Ultra-Processed Foods", "Weight Management"],
    takeaways: [
      "Fructose is metabolised exclusively in the liver and drives de novo lipogenesis, hepatic insulin resistance, and NAFLD",
      "A calorie of fructose is not metabolically equivalent to a calorie of glucose",
      "Sugar-sweetened beverages are the single dietary factor most consistently associated with type 2 diabetes risk",
      "Reducing added sugar intake improves metabolic markers within 9 days in children — independent of caloric intake",
    ],
    relatedDiets: ["Low-Carbohydrate Diet", "Whole Food Diet"],
    youtubeId: "t7PIURKDTes",
  },
  {
    id: "v11",
    title: "The DASH Diet: Evidence for Blood Pressure and Beyond",
    channel: "Harvard T.H. Chan School of Public Health",
    duration: "44m",
    year: 2022,
    speaker: "Walter Willett",
    speakerShort: "Willett",
    description:
      "Willett reviews the DASH (Dietary Approaches to Stop Hypertension) trial and its successors, showing that the DASH dietary pattern reduces systolic blood pressure by 8–14 mmHg — comparable to first-line antihypertensive medication. He covers the key components (sodium reduction, potassium, magnesium, calcium), and the evidence for DASH beyond blood pressure including kidney disease and cardiovascular outcomes.",
    topics: ["DASH Protocol", "Cardiovascular Health", "Dietary Patterns"],
    takeaways: [
      "The original DASH trial showed 8 mmHg reduction in systolic BP — comparable to single-drug antihypertensive therapy",
      "DASH-Sodium trial showed additional 4–6 mmHg reduction when sodium was restricted to 1500mg/day",
      "DASH diet reduces 10-year cardiovascular risk by approximately 20% in observational studies",
      "Potassium (from fruits and vegetables) is as important as sodium restriction for blood pressure control",
    ],
    relatedDiets: ["DASH Protocol", "Mediterranean Diet"],
    youtubeId: "avYByq1fMKc",
  },
  {
    id: "v12",
    title: "Plant-Based Diets: Health Benefits and Nutritional Considerations",
    channel: "Stanford Medicine",
    duration: "1h 16m",
    year: 2023,
    speaker: "Christopher Gardner",
    speakerShort: "Gardner",
    description:
      "Gardner reviews the evidence on plant-based dietary patterns — from vegetarian and vegan diets to flexitarian approaches. He covers the cardiovascular, metabolic, and cancer prevention benefits, the nutritional considerations (B12, omega-3, iron, zinc, calcium), and presents data from his own SWAP-MEAT trial comparing plant-based vs animal-based protein.",
    topics: ["Plant-Based Diets", "Cardiovascular Health", "Cancer Prevention"],
    takeaways: [
      "SWAP-MEAT trial showed plant-based protein (Beyond Meat) vs animal protein improved TMAO, LDL-C, and body weight at 8 weeks",
      "Vegetarian and vegan diets are associated with 15–20% lower all-cause mortality in prospective cohort studies",
      "B12 supplementation is mandatory for vegans — deficiency is universal without supplementation",
      "Not all plant-based foods are equal — ultra-processed plant foods do not confer the same benefits as whole plant foods",
    ],
    relatedDiets: ["Plant-Based Diet", "Vegan Diet", "Mediterranean Diet"],
    youtubeId: "dWh_YFv8fO8",
  },
  {
    id: "v13",
    title: "Omega-3 Fatty Acids: What the Trials Actually Show",
    channel: "FoundMyFitness",
    duration: "1h 12m",
    year: 2022,
    speaker: "Rhonda Patrick",
    speakerShort: "Patrick",
    description:
      "Patrick covers the VITAL trial (25,871 participants, 5-year follow-up), the REDUCE-IT trial, and the STRENGTH trial — presenting a balanced view of the omega-3 evidence. She covers EPA vs DHA, the omega-3 index, dietary sources vs supplementation, and why fish consumption data consistently shows benefit even when isolated supplements do not.",
    topics: ["Micronutrients", "Cardiovascular Health", "Inflammation"],
    takeaways: [
      "VITAL trial showed no significant reduction in major cardiovascular events with 1g/day omega-3 in primary prevention",
      "REDUCE-IT showed 25% reduction with 4g/day EPA — but the mineral oil placebo raised LDL in the control group",
      "Omega-3 index (EPA+DHA as % of RBC fatty acids) is a better predictor of cardiovascular risk than plasma levels",
      "Dietary fish consumption (2+ servings/week) consistently reduces cardiovascular mortality in observational data",
    ],
    relatedDiets: ["Mediterranean Diet", "Nordic Diet"],
    youtubeId: "nmReeTIZMos",
  },
  {
    id: "v14",
    title: "The Ketogenic Diet: Evidence, Mechanisms, and Limits",
    channel: "Peter Attia MD",
    duration: "1h 34m",
    year: 2022,
    speaker: "Peter Attia",
    speakerShort: "Attia",
    description:
      "Attia presents a rigorous review of the ketogenic diet evidence — covering the metabolic mechanisms of ketosis, the RCT data on weight loss and type 2 diabetes reversal, the effects on lipid profiles (including the LDL-C rise in some individuals), and the practical considerations for long-term adherence.",
    topics: ["Metabolic Health", "Weight Management", "Dietary Patterns"],
    takeaways: [
      "Ketogenic diets consistently outperform low-fat diets for short-term weight loss (6–12 months) in RCTs",
      "Virta Health trial showed 60% of type 2 diabetics achieved remission on ketogenic diet at 2 years",
      "LDL-C rises in approximately 30% of individuals on ketogenic diets — ApoB and LDL-P should be monitored",
      "Long-term adherence is the primary limitation — most RCTs show convergence of outcomes at 2+ years",
    ],
    relatedDiets: ["Ketogenic Diet", "Low-Carbohydrate Diet"],
    youtubeId: "jW0cVEgW9YY",
  },
  {
    id: "v15",
    title: "Diet and Cancer: Separating Evidence from Noise",
    channel: "Memorial Sloan Kettering",
    duration: "1h 8m",
    year: 2023,
    speaker: "David Katz",
    speakerShort: "Katz",
    description:
      "Dr David Katz, founding director of Yale University's Prevention Research Center, reviews the evidence on diet and cancer risk. He covers the WCRF/AICR evidence grading system, the strongest dietary risk factors (processed meat, alcohol, obesity), the protective factors (fibre, cruciferous vegetables, Mediterranean pattern), and why the epidemiology of diet and cancer is genuinely difficult.",
    topics: ["Cancer Prevention", "Dietary Patterns", "Inflammation"],
    takeaways: [
      "Processed meat is classified as Group 1 carcinogen (colorectal cancer) by IARC — 50g/day increases risk by ~18%",
      "Obesity is the second leading preventable cause of cancer after smoking — dietary patterns that prevent obesity reduce cancer risk",
      "Fibre intake is inversely associated with colorectal cancer in a dose-dependent manner",
      "No single food causes or prevents cancer — dietary pattern and overall lifestyle context matter most",
    ],
    relatedDiets: ["Mediterranean Diet", "Plant-Based Diet"],
    youtubeId: "5qxyL-eMUEc",
  },
  {
    id: "v16",
    title: "Nutrition and Cognitive Health: What the Evidence Shows",
    channel: "FoundMyFitness",
    duration: "1h 24m",
    year: 2023,
    speaker: "Rhonda Patrick",
    speakerShort: "Patrick",
    description:
      "Patrick reviews the evidence on diet and brain health — covering the MIND diet (a hybrid of Mediterranean and DASH designed for cognitive protection), the role of omega-3 DHA in neuronal membrane integrity, the evidence on sulforaphane and BDNF, and the FINGER trial showing that a multi-domain lifestyle intervention (including diet) can prevent cognitive decline.",
    topics: ["Cognitive Health", "Mediterranean Diet", "Micronutrients"],
    takeaways: [
      "MIND diet adherence associated with 53% lower risk of Alzheimer's disease in prospective cohort study",
      "FINGER trial (RCT) showed 25% improvement in cognitive composite score with multi-domain lifestyle intervention including diet",
      "DHA is the dominant omega-3 in the brain — low DHA status is associated with accelerated cognitive decline",
      "Sulforaphane increases BDNF (brain-derived neurotrophic factor) in animal models and small human trials",
    ],
    relatedDiets: ["MIND Diet", "Mediterranean Diet"],
    youtubeId: "bhkxidN2M9Q",
  },
  {
    id: "v17",
    title: "Inflammation and Diet: The Anti-Inflammatory Evidence",
    channel: "ZOE Science & Nutrition",
    duration: "48m",
    year: 2023,
    speaker: "Tim Spector",
    speakerShort: "Spector",
    description:
      "Spector reviews the evidence on dietary patterns and systemic inflammation — covering the Dietary Inflammatory Index (DII), the foods and nutrients most consistently associated with reduced CRP and IL-6, and the ZOE PREDICT data on postprandial inflammation. He argues that inflammation is a key mediator between diet and chronic disease.",
    topics: ["Inflammation", "Gut Microbiome", "Dietary Patterns"],
    takeaways: [
      "The Dietary Inflammatory Index (DII) predicts CRP levels — high-DII diets are associated with 40% higher cardiovascular risk",
      "Polyphenols (from berries, olive oil, dark chocolate) consistently reduce inflammatory markers in RCTs",
      "Ultra-processed foods increase postprandial inflammation independent of macronutrient content",
      "Gut microbiome diversity mediates a significant portion of the diet-inflammation relationship",
    ],
    relatedDiets: ["Mediterranean Diet", "Anti-Inflammatory Diet"],
    youtubeId: "TT5ig1EiIfQ",
  },
  {
    id: "v18",
    title: "Vitamin D and Metabolic Health: The VITAL Trial and Beyond",
    channel: "FoundMyFitness",
    duration: "1h 1m",
    year: 2022,
    speaker: "Rhonda Patrick",
    speakerShort: "Patrick",
    description:
      "Patrick reviews the VITAL trial (25,871 participants, 5-year follow-up) on vitamin D3 supplementation, the evidence on vitamin D and type 2 diabetes prevention, and why the RDA of 600 IU is almost certainly insufficient for optimal health. She covers the 2000+ genes regulated by vitamin D and the evidence for optimal serum 25(OH)D levels.",
    topics: ["Micronutrients", "Metabolic Health", "Inflammation"],
    takeaways: [
      "VITAL trial showed vitamin D3 (2000 IU/day) reduced cancer mortality by 25% and autoimmune disease risk by 22%",
      "Approximately 40% of the US population is vitamin D deficient (<20 ng/mL) — higher in darker-skinned individuals",
      "Optimal serum 25(OH)D for health outcomes is likely 40–60 ng/mL, not the 20 ng/mL defined as 'sufficient'",
      "Vitamin D functions as a hormone — it regulates gene expression in virtually every tissue in the body",
    ],
    relatedDiets: ["Mediterranean Diet", "Whole Food Diet"],
    youtubeId: "tBSfIckPV44",
  },
  {
    id: "v19",
    title: "The Nordic Diet: Sustainability and Health Evidence",
    channel: "Harvard T.H. Chan School of Public Health",
    duration: "52m",
    year: 2022,
    speaker: "Walter Willett",
    speakerShort: "Willett",
    description:
      "Willett presents the evidence on the Nordic dietary pattern — a regionally adapted diet based on whole grains (rye, oats, barley), fatty fish, root vegetables, berries, and rapeseed oil. He covers the SYSDIET trial data, the cardiovascular and metabolic benefits, and why the Nordic diet is considered one of the most environmentally sustainable dietary patterns.",
    topics: ["Dietary Patterns", "Cardiovascular Health", "Metabolic Health"],
    takeaways: [
      "SYSDIET trial showed Nordic diet improved blood lipids, blood pressure, and inflammatory markers vs control diet",
      "Nordic diet has a significantly lower carbon footprint than Western dietary patterns",
      "Whole grain rye is associated with lower postprandial glucose response than wheat bread — relevant to metabolic health",
      "Berry consumption (rich in anthocyanins) is a distinctive Nordic component associated with reduced cardiovascular risk",
    ],
    relatedDiets: ["Nordic Diet", "Mediterranean Diet"],
    youtubeId: "VIEyrcwiGUo",
  },
  {
    id: "v20",
    title: "Functional Medicine and Diet: What the Evidence Supports",
    channel: "Mark Hyman MD",
    duration: "1h 18m",
    year: 2023,
    speaker: "Mark Hyman",
    speakerShort: "Hyman",
    description:
      "Dr Mark Hyman, Director of the Cleveland Clinic Center for Functional Medicine, presents his food-as-medicine framework. He covers the evidence for dietary interventions in type 2 diabetes reversal, the Pegan diet (a hybrid of Paleo and vegan principles), and the Cleveland Clinic Food as Medicine trial showing that medically tailored meals reduce hospitalisation rates by 16%.",
    topics: ["Metabolic Health", "Dietary Patterns", "Inflammation"],
    takeaways: [
      "Cleveland Clinic Food as Medicine trial showed medically tailored meals reduced hospitalisation by 16% and healthcare costs by $9,000/year",
      "Type 2 diabetes reversal (HbA1c <6.5% off medication) is achievable through dietary intervention alone in a significant proportion of patients",
      "The Pegan diet emphasises low-glycaemic load, high phytonutrient density, and adequate protein — consistent with multiple evidence-based frameworks",
      "Food quality (nutrient density, processing level) is more important than macronutrient ratio for most metabolic outcomes",
    ],
    relatedDiets: ["Whole Food Diet", "Paleo Diet", "Plant-Based Diet"],
    youtubeId: "UyneMnERmnI",
  },
  {
    id: "v21",
    title: "The TRUTH About Food",
    channel: "SUNY Downstate Health Sciences University",
    duration: "1h 14m",
    year: 2019,
    speaker: "David Katz",
    speakerShort: "Katz",
    description:
      "Dr David Katz, founding director of the Yale-Griffin Prevention Research Center, presents a comprehensive overview of what the totality of nutrition science actually shows — cutting through diet wars to identify the dietary patterns with the strongest evidence base for disease prevention and longevity.",
    topics: ["Dietary Patterns", "Plant-Based Diets", "Food Policy"],
    takeaways: [
      "The overall quality of the diet — not any single nutrient — is the strongest predictor of chronic disease risk",
      "Diets emphasising whole plants, minimally processed foods, and limited added sugar consistently outperform single-nutrient interventions",
      "Diet quality indices (such as the AHEI) predict mortality more reliably than any individual food or nutrient marker",
      "The diet wars are largely manufactured — the evidence for a whole-food, predominantly plant-based diet is robust across multiple frameworks",
    ],
    relatedDiets: ["Mediterranean Diet", "DASH Diet", "Plant-Based Diet"],
    youtubeId: "-YLaJZk2Icc",
  },
  {
    id: "v22",
    title: "A History of Nutrition Science: Implications for Current Research, Dietary Guidelines, and Food Policy",
    channel: "Low Carb Down Under",
    duration: "26m",
    year: 2019,
    speaker: "Dariush Mozaffarian",
    speakerShort: "Mozaffarian",
    description:
      "Dr Dariush Mozaffarian, Dean of the Tufts Friedman School of Nutrition Science and Policy, traces the history of nutrition science and its policy implications — explaining how past errors in dietary guidelines were made, what the current evidence shows, and what a modern evidence-based food policy framework should look like.",
    topics: ["Food Policy", "Dietary Patterns", "Ultra-Processed Foods"],
    takeaways: [
      "Early dietary guidelines focused excessively on single nutrients (fat, cholesterol) rather than food quality and dietary patterns",
      "Ultra-processed foods are the dominant driver of diet-related disease globally — more than any single nutrient",
      "Food policy interventions (taxes, subsidies, labelling) have measurable effects on population dietary behaviour",
      "The next generation of dietary guidelines must shift from nutrient-based to food-based recommendations",
    ],
    relatedDiets: ["Whole Food Diet", "Mediterranean Diet", "DASH Diet"],
    youtubeId: "7JOQUpATCXA",
  },
  {
    id: "v23",
    title: "Optimal Diets for Personal & Planetary Health",
    channel: "Harvard University",
    duration: "56m",
    year: 2022,
    speaker: "Frank Hu",
    speakerShort: "Hu",
    description:
      "Dr Frank Hu, Chair of the Department of Nutrition at Harvard T.H. Chan School of Public Health, presents the evidence on optimal dietary patterns for both human health and environmental sustainability — covering the EAT-Lancet planetary health diet, type 2 diabetes prevention, and the convergence between healthy and sustainable eating.",
    topics: ["Dietary Patterns", "Metabolic Health", "Plant-Based Diets"],
    takeaways: [
      "Dietary patterns that reduce type 2 diabetes risk (Mediterranean, DASH, plant-based) also have lower environmental footprints",
      "Replacing red and processed meat with plant proteins is the single dietary change with the largest combined health and environmental benefit",
      "The EAT-Lancet planetary health diet is consistent with existing evidence-based dietary guidelines for chronic disease prevention",
      "Diet quality scores (AHEI, AMED, DASH) predict all-cause mortality independently of individual food or nutrient intake",
    ],
    relatedDiets: ["Mediterranean Diet", "Plant-Based Diet", "DASH Diet"],
    youtubeId: "842Lk9Q7TfQ",
  },
  {
    id: "v24",
    title: "Personalized Medicine Based on Deep Human Phenotyping",
    channel: "Wellcome Connecting Science",
    duration: "1h 1m",
    year: 2022,
    speaker: "Eran Segal",
    speakerShort: "Segal",
    description:
      "Prof Eran Segal of the Weizmann Institute of Science presents the landmark Personalised Nutrition Project — showing that postprandial glucose responses to identical foods vary dramatically between individuals, and that gut microbiome composition can predict these responses better than standard glycaemic index values.",
    topics: ["Personalised Nutrition", "Gut Microbiome", "Metabolic Health"],
    takeaways: [
      "Glucose responses to identical meals vary up to 10-fold between individuals — standard GI values are population averages that may not apply to any given person",
      "Gut microbiome composition predicts postprandial glucose responses more accurately than meal composition alone",
      "Personalised dietary recommendations based on microbiome and CGM data outperform standard dietitian advice in glycaemic control",
      "The same food can be healthy for one person and harmful for another — personalisation is not optional for optimal nutrition",
    ],
    relatedDiets: ["Low-Glycaemic Diet", "Mediterranean Diet", "Gut Health Diet"],
    youtubeId: "u0_ZGXCsdC8",
  },
  {
    id: "v25",
    title: "The Most Honest Man In Nutrition Research",
    channel: "Doctor Mike",
    duration: "2h 41m",
    year: 2025,
    speaker: "Kevin Hall",
    speakerShort: "Hall",
    description:
      "Dr Kevin Hall, Senior Investigator at the NIH National Institute of Diabetes and Digestive and Kidney Diseases, discusses his landmark randomised controlled trial comparing ultra-processed and unprocessed diets — the first RCT to show that ultra-processed food causes excess calorie intake and weight gain independent of macronutrient composition.",
    topics: ["Ultra-Processed Foods", "Weight Management", "Metabolic Health"],
    takeaways: [
      "The NIH ultra-processed food RCT found participants consumed ~500 kcal/day more on ultra-processed diets despite matched macronutrients — and gained 0.9 kg in 2 weeks",
      "Ultra-processed food drives excess intake through mechanisms beyond macronutrient composition — likely food texture, eating rate, and palatability",
      "The carbohydrate-insulin model does not fully explain the results — fat and carbohydrate were equally affected",
      "Randomised controlled trials of dietary patterns are feasible and necessary to establish causality beyond epidemiological associations",
    ],
    relatedDiets: ["Whole Food Diet", "NOVA Classification Diet"],
    youtubeId: "WBllzAb_vAk",
  },
  {
    id: "v26",
    title: "Carbohydrate-Insulin Model of Obesity",
    channel: "The Texas Heart Institute",
    duration: "38m",
    year: 2023,
    speaker: "David Ludwig",
    speakerShort: "Ludwig",
    description:
      "Dr David Ludwig, Professor at Harvard Medical School and Boston Children's Hospital, presents the carbohydrate-insulin model of obesity — arguing that dietary carbohydrate quality and quantity drive insulin secretion, which promotes fat storage and hunger, independent of total calorie intake.",
    topics: ["Weight Management", "Metabolic Health", "Dietary Patterns"],
    takeaways: [
      "The carbohydrate-insulin model proposes that high-glycaemic carbohydrates drive fat storage through insulin signalling, independent of calorie intake",
      "Low-carbohydrate diets may have a metabolic advantage for weight loss beyond calorie restriction alone",
      "Dietary glycaemic load is a stronger predictor of metabolic outcomes than total fat or total carbohydrate intake",
      "The energy balance model and the carbohydrate-insulin model are not mutually exclusive — both mechanisms likely contribute to obesity",
    ],
    relatedDiets: ["Low-Carbohydrate Diet", "Ketogenic Diet", "Low-Glycaemic Diet"],
    youtubeId: "M-He7gyO2xQ",
  },
  {
    id: "v27",
    title: "Circadian Theory of Health",
    channel: "Salk Institute",
    duration: "55m",
    year: 2018,
    speaker: "Satchin Panda",
    speakerShort: "Panda",
    description:
      "Dr Satchin Panda, Professor at the Salk Institute for Biological Studies, presents the circadian theory of health — showing that when we eat is as important as what we eat. He covers the evidence for time-restricted eating (TRE) in improving metabolic health, weight, blood pressure, and sleep quality.",
    topics: ["Circadian Biology", "Intermittent Fasting", "Metabolic Health"],
    takeaways: [
      "Time-restricted eating (eating within an 8–10 hour window) improves metabolic markers independent of calorie restriction",
      "Circadian misalignment — eating late at night — disrupts glucose metabolism, lipid profiles, and gut microbiome composition",
      "The liver, gut, and muscle all have circadian clocks that are entrained by meal timing as well as light",
      "TRE studies in humans show improvements in weight, blood pressure, insulin sensitivity, and sleep quality within 12 weeks",
    ],
    relatedDiets: ["Intermittent Fasting", "Time-Restricted Eating"],
    youtubeId: "LJ9Ae_j_kjI",
  },
  {
    id: "v28",
    title: "Food, Nutrition and Politics: A Conversation with Marion Nestle",
    channel: "UCTV (University of California Television)",
    duration: "52m",
    year: 2019,
    speaker: "Marion Nestle",
    speakerShort: "Nestle",
    description:
      "Prof Marion Nestle, Paulette Goddard Professor Emerita of Nutrition, Food Studies, and Public Health at NYU, discusses the political and commercial forces that shape dietary guidelines and food policy — and why the science of nutrition is so frequently distorted by industry influence.",
    topics: ["Food Policy", "Ultra-Processed Foods", "Dietary Patterns"],
    takeaways: [
      "Food industry funding of nutrition research systematically biases results toward industry-favourable conclusions",
      "Dietary guidelines are a political document as much as a scientific one — industry lobbying shapes every edition",
      "The single most effective public health nutrition intervention is reducing ultra-processed food consumption at a population level",
      "Consumers cannot be expected to navigate a food environment designed to maximise consumption of the least healthy products",
    ],
    relatedDiets: ["Whole Food Diet", "NOVA Classification Diet"],
    youtubeId: "43crDb4tbLg",
  },
  {
    id: "v29",
    title: "A Nutritional Approach for Reversing Diabetes",
    channel: "Physicians Committee",
    duration: "20m",
    year: 2020,
    speaker: "Neal Barnard",
    speakerShort: "Barnard",
    description:
      "Dr Neal Barnard, President of the Physicians Committee for Responsible Medicine and Adjunct Professor at George Washington University, presents the clinical evidence for plant-based dietary intervention in type 2 diabetes reversal — including his randomised trial showing that a low-fat vegan diet outperforms the standard ADA diet for glycaemic control.",
    topics: ["Plant-Based Diets", "Metabolic Health", "Dietary Patterns"],
    takeaways: [
      "A low-fat vegan diet reduced HbA1c by 1.23 percentage points — significantly more than the standard ADA diet in a head-to-head RCT",
      "Plant-based diets improve insulin sensitivity through reduced intramyocellular lipid accumulation",
      "Dietary fibre from whole plant foods feeds beneficial gut bacteria that produce short-chain fatty acids improving glucose metabolism",
      "Type 2 diabetes is not inevitably progressive — dietary intervention can achieve remission in a significant proportion of patients",
    ],
    relatedDiets: ["Vegan Diet", "Plant-Based Diet", "Low-Fat Diet"],
    youtubeId: "tAiXvrIMIIE",
  },
  {
    id: "v30",
    title: "Lifestyle Medicine with Dr Dean Ornish",
    channel: "UCLA Health",
    duration: "22m",
    year: 2018,
    speaker: "Dean Ornish",
    speakerShort: "Ornish",
    description:
      "Dr Dean Ornish, Clinical Professor of Medicine at UCSF, presents the evidence for his comprehensive lifestyle medicine programme — the first intervention shown to reverse coronary artery disease without drugs or surgery. He covers the dietary components, the role of stress management and social support, and the emerging evidence on telomere length and gene expression.",
    topics: ["Cardiovascular Health", "Plant-Based Diets", "Longevity"],
    takeaways: [
      "The Ornish Programme is the only dietary intervention with Level 1 evidence for reversing coronary artery disease",
      "A very low-fat whole-food plant-based diet combined with stress management and social support reverses atherosclerosis in 82% of patients",
      "Lifestyle intervention increases telomere length — the first evidence that any intervention can slow biological ageing at the chromosomal level",
      "Medicare covers the Ornish Programme — the first lifestyle medicine programme to receive CMS reimbursement",
    ],
    relatedDiets: ["Ornish Diet", "Plant-Based Diet", "Low-Fat Diet"],
    youtubeId: "PtLv6hRwAN4",
  },
  {
    id: "v31",
    title: "Elements of a Healthy and Sustainable Diet",
    channel: "EAT",
    duration: "23m",
    year: 2014,
    speaker: "Walter Willett",
    speakerShort: "Willett",
    description:
      "Prof Walter Willett presents the scientific foundations of the EAT-Lancet planetary health diet — explaining how the same dietary shifts that reduce chronic disease risk also dramatically reduce the environmental impact of food production, and why this convergence makes the case for dietary change more compelling than ever.",
    topics: ["Dietary Patterns", "Plant-Based Diets", "Food Policy"],
    takeaways: [
      "Diets high in plant foods and low in animal products reduce both chronic disease risk and greenhouse gas emissions",
      "Replacing red meat with plant proteins is the single dietary change with the largest combined health and environmental benefit",
      "The EAT-Lancet reference diet allows for modest amounts of animal foods — it is not a vegan diet",
      "Achieving the planetary health diet globally would prevent 11 million premature deaths per year",
    ],
    relatedDiets: ["Mediterranean Diet", "Plant-Based Diet", "EAT-Lancet Diet"],
    youtubeId: "bYna_V0Sq6c",
  },
  {
    id: "v32",
    title: "Why I Changed My Mind About Vitamin D & Sunlight",
    channel: "ZOE",
    duration: "52m",
    year: 2025,
    speaker: "Tim Spector",
    speakerShort: "Spector",
    description:
      "Prof Tim Spector, Professor of Genetic Epidemiology at King's College London and co-founder of ZOE, revisits the evidence on vitamin D supplementation — explaining why large RCTs have failed to confirm the benefits seen in observational studies, and what this tells us about the limits of single-nutrient thinking in nutrition science.",
    topics: ["Micronutrients", "Personalised Nutrition", "Dietary Patterns"],
    takeaways: [
      "Large RCTs of vitamin D supplementation have largely failed to confirm the benefits seen in observational studies",
      "Confounding by sun exposure, outdoor activity, and diet quality explains much of the observational association between vitamin D and health",
      "The failure of vitamin D RCTs is a case study in the limits of single-nutrient thinking — the food matrix matters",
      "Personalised approaches based on baseline deficiency are more likely to show benefit than population-wide supplementation",
    ],
    relatedDiets: ["Mediterranean Diet", "Whole Food Diet"],
    youtubeId: "bByTKLZcI20",
  },
  {
    id: "v33",
    title: "How Different Diets Impact Your Health",
    channel: "Andrew Huberman",
    duration: "24m",
    year: 2025,
    speaker: "Christopher Gardner",
    speakerShort: "Gardner",
    description:
      "Dr Christopher Gardner, Professor of Medicine at Stanford, summarises the key findings from his dietary pattern research — including the DIETFITS trial comparing low-fat and low-carbohydrate diets, and the SWAP-MEAT trial comparing animal and plant-based proteins — explaining what the evidence shows about which dietary patterns work best and for whom.",
    topics: ["Dietary Patterns", "Weight Management", "Plant-Based Diets"],
    takeaways: [
      "The DIETFITS trial found no significant difference in weight loss between low-fat and low-carbohydrate diets at 12 months",
      "Individual variation in response to dietary patterns is large — insulin secretion status and gut microbiome may predict who responds to which diet",
      "Plant-based meat substitutes matched animal meat for weight loss and cardiovascular risk markers in the SWAP-MEAT trial",
      "Diet quality — not macronutrient ratio — is the most consistent predictor of health outcomes across dietary pattern trials",
    ],
    relatedDiets: ["Low-Carbohydrate Diet", "Low-Fat Diet", "Plant-Based Diet"],
    youtubeId: "9vQZT2igXN4",
  },
  {
    id: "v34",
    title: "Sulforaphane and Its Effects on Cancer, Mortality, Aging, Brain and Behavior, Heart Disease & More",
    channel: "FoundMyFitness",
    duration: "1h 10m",
    year: 2016,
    speaker: "Rhonda Patrick",
    speakerShort: "Patrick",
    description:
      "Dr Rhonda Patrick presents a comprehensive review of the evidence on sulforaphane — the bioactive compound in cruciferous vegetables, particularly broccoli sprouts — covering its mechanisms of action in cancer prevention, neuroinflammation, cardiovascular protection, and ageing.",
    topics: ["Cancer Prevention", "Phytonutrients", "Inflammation"],
    takeaways: [
      "Sulforaphane activates the Nrf2 pathway, upregulating over 200 cytoprotective genes involved in antioxidant defence and detoxification",
      "Broccoli sprouts contain 20–100x more sulforaphane precursor (glucoraphanin) than mature broccoli",
      "Epidemiological studies show cruciferous vegetable consumption is associated with reduced risk of lung, colorectal, breast, and prostate cancer",
      "Myrosinase enzyme (destroyed by cooking) is required to convert glucoraphanin to sulforaphane — add raw mustard seed or eat sprouts raw",
    ],
    relatedDiets: ["Mediterranean Diet", "Plant-Based Diet", "Whole Food Diet"],
    youtubeId: "zz4YVJ4aRfg",
  },
  {
    id: "v35",
    title: "Insulin Resistance Masterclass: The Full Body Impact of Metabolic Dysfunction",
    channel: "Peter Attia MD",
    duration: "2h 34m",
    year: 2025,
    speaker: "Peter Attia",
    speakerShort: "Attia",
    description:
      "Dr Peter Attia, physician and longevity researcher, presents a comprehensive masterclass on insulin resistance — covering its mechanisms, its role in cardiovascular disease, cancer, neurodegeneration, and all-cause mortality, and the dietary and lifestyle interventions with the strongest evidence for reversal.",
    topics: ["Metabolic Health", "Cardiovascular Health", "Longevity"],
    takeaways: [
      "Insulin resistance is present in approximately 40% of US adults and is the root cause of most chronic metabolic disease",
      "HOMA-IR, fasting insulin, and triglyceride:HDL ratio are more sensitive early markers of metabolic dysfunction than fasting glucose or HbA1c",
      "Zone 2 aerobic exercise is the most potent single intervention for improving mitochondrial function and insulin sensitivity",
      "Dietary carbohydrate restriction and time-restricted eating both improve insulin sensitivity through complementary mechanisms",
    ],
    relatedDiets: ["Low-Carbohydrate Diet", "Mediterranean Diet", "Time-Restricted Eating"],
    youtubeId: "vYQaLV3Fm00",
  },
  {
    id: "v36",
    title: "Type 2 Diabetes Is 'Processed Food Disease'",
    channel: "CrossFit",
    duration: "31m",
    year: 2017,
    speaker: "Robert Lustig",
    speakerShort: "Lustig",
    description:
      "Dr Robert Lustig, Professor Emeritus of Paediatric Endocrinology at UCSF, presents the case that type 2 diabetes is primarily a disease of ultra-processed food consumption — driven by fructose-induced hepatic insulin resistance, not excess calorie intake per se.",
    topics: ["Metabolic Health", "Ultra-Processed Foods", "Weight Management"],
    takeaways: [
      "Fructose (from added sugar) is metabolised exclusively in the liver, driving de novo lipogenesis, hepatic insulin resistance, and visceral fat accumulation",
      "A 9-day reduction in dietary sugar (replacing with starch) improved all metabolic markers in obese children without calorie restriction",
      "Ultra-processed foods are engineered to be hyperpalatable and to override satiety signalling — making overconsumption the default",
      "The food industry's substitution of fat with sugar in low-fat products drove the obesity and diabetes epidemic of the 1980s–2000s",
    ],
    relatedDiets: ["Low-Sugar Diet", "Whole Food Diet", "NOVA Classification Diet"],
    youtubeId: "f1oRlVKwrio",
  },
  {
    id: "v37",
    title: "Fasting Mimicking Diet Cycles, Multi System Reprogramming and Disease",
    channel: "Stanford Department of Medicine",
    duration: "33m",
    year: 2024,
    speaker: "Valter Longo",
    speakerShort: "Longo",
    description:
      "Prof Valter Longo, Director of the USC Longevity Institute, presents the latest clinical evidence for the Fasting Mimicking Diet (FMD) — a 5-day, calorie-restricted, plant-based protocol that triggers fasting-like cellular reprogramming while allowing food intake, with clinical trials showing benefits in cancer, autoimmune disease, metabolic syndrome, and biological ageing.",
    topics: ["Longevity", "Intermittent Fasting", "Metabolic Health"],
    takeaways: [
      "Three cycles of the 5-day FMD reduced visceral fat, blood pressure, fasting glucose, and IGF-1 in a randomised trial of 100 adults",
      "FMD triggers autophagy, stem cell activation, and immune system regeneration — mechanisms not activated by simple calorie restriction",
      "Periodic fasting (rather than chronic calorie restriction) preserves lean mass while reducing fat mass and metabolic risk factors",
      "Clinical trials of FMD in cancer patients show improved chemotherapy tolerance and tumour response rates",
    ],
    relatedDiets: ["Longevity Diet", "Fasting Mimicking Diet", "Mediterranean Diet"],
    youtubeId: "FXbanqer1fQ",
  },
  {
    id: "v38",
    title: "How to Make Better Food Choices for Health & Longevity",
    channel: "Huberman Lab Clips",
    duration: "1h 42m",
    year: 2025,
    speaker: "Andrew Huberman",
    speakerShort: "Huberman",
    description:
      "Dr Andrew Huberman, Professor of Neurobiology at Stanford, discusses practical nutrition protocols for health and longevity — covering the evidence on time-restricted eating, protein intake, micronutrient density, and the neuroscience of food reward and satiety.",
    topics: ["Dietary Patterns", "Metabolic Health", "Longevity"],
    takeaways: [
      "Time-restricted eating within an 8–10 hour window improves metabolic health markers independent of calorie intake",
      "Protein intake of 1.6–2.2g/kg/day is optimal for muscle protein synthesis and satiety across age groups",
      "Highly processed foods activate dopamine reward circuits in ways that whole foods do not — driving overconsumption through neurological mechanisms",
      "Micronutrient density (vitamins, minerals, polyphenols) is a more useful lens for food quality than macronutrient composition alone",
    ],
    relatedDiets: ["Whole Food Diet", "Mediterranean Diet", "Time-Restricted Eating"],
    youtubeId: "O0NfM09bGuo",
  },
  {
    id: "v39",
    title: "How to Exercise & Eat for Optimal Health & Longevity",
    channel: "Andrew Huberman",
    duration: "4h 4m",
    year: 2025,
    speaker: "Gabrielle Lyon",
    speakerShort: "Lyon",
    description:
      "Dr Gabrielle Lyon, founder of the Institute for Muscle-Centric Medicine, presents the evidence for skeletal muscle as the primary organ of metabolic health — arguing that protein intake, resistance training, and muscle mass are the most important levers for longevity, metabolic health, and healthy ageing in women.",
    topics: ["Protein & Muscle", "Longevity", "Metabolic Health"],
    takeaways: [
      "Skeletal muscle is the largest glucose disposal organ in the body — muscle mass is the strongest predictor of insulin sensitivity",
      "Protein intake of ≥1.6g/kg/day is required to maintain muscle mass during weight loss — standard dietary guidelines are insufficient",
      "The first meal of the day should contain ≥30–40g of protein to maximally stimulate muscle protein synthesis",
      "Muscle mass, not fat mass, is the primary determinant of metabolic rate and long-term weight management success",
    ],
    relatedDiets: ["High-Protein Diet", "Carnivore Diet", "Whole Food Diet"],
    youtubeId: "WFcYF_pxLgA",
  },
];
